install.packages("usethis")
library(usethis)
use_git_config(user.name = 'EricCacciavillani', user.email='eric.cacciavillani@gmail.com')
git_sitrep()
create_github_token()
install.packages("credentials")
library(credentials)
set_github_pat()
install.packages("devtools")
devtools::install_github("hadley/devtools")
library(devtools)
library(blogbuilder)
library(distill)
library(postcards)
install.packages("create_postcard")
postcards::create_postcard(file = "/Users/ericcacciavillani/Desktop/Coding/R Programming/Postcard/DACSS601August2021/users/Eric-Cacciavillani.Rmd", template = "jolla")
